# Shared for all services

eureka:
  instance:
    prefer-ip-address:  true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
      
    

#access actuator endpoints without requiring authentication
management:
  security:
    enabled: false
    
