# Shared for all services

eureka:
  instance:
    prefer-ip-address:  true
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:8761/eureka
      
    

# access actuator endpoints without requiring authentication
management:
  security:
    enabled: false
    

# zipkin service name
spring:    
  zipkin:
    service:
      name: zipkin-service